Tim's First Pull Request OMG OMG
usdevs/usc-website-hackathon-frontend pull request #141
Opened 2023-12-07 13:22 UTC by tim-pipi

### Changes

Added "Team Members" section in the `README.md` file.

2023-12-07 13:22 UTC, peasantbird approved these changes
LGTM

2023-12-07 13:25 UTC, m1oojv requested changes
lint error

2023-12-07 13:25 UTC, m1oojv commented on README.md
> +1. Timothy Putra Prasetio
Can u correct the styling to satisfy prettier linter

2023-12-12 14:06 UTC, zsh-eng commented
No need to clear the linting rules. Good job mr tim ! :D

2023-12-12 14:06 UTC, closed without merging